name: CI/CD for sustify backend

on:
    push:
        branches:
            - "master"

env:
    DOCKER_IMAGE_NAME: sustify-backend
    DOCKER_PORT: 8080

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: ghcr.io

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ghcr.io/${{ github.repository }}:${{ github.run_id }}


    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Print variables
              run: |
                  echo "DOCKER_IMAGE_NAME: $DOCKER_IMAGE_NAME"
                  echo "DOCKER_PORT: $DOCKER_PORT"
                  echo "Github repository: ${{ github.repository }}"
                  echo "Github run ID: ${{ github.run_id }}"

            - name: Execute SSH commands
              uses: appleboy/ssh-action@master
              env:
                  DOCKER_IMAGE_NAME: sustify-backend
                  DOCKER_PORT: 8080
              with:
                host: ${{ secrets.HOST_NAME }}
                username: root
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                  DOCKER_IMAGE_NAME=sustify-backend
                  DOCKER_PORT=8080
                  echo "DOCKER_IMAGE_NAME: $DOCKER_IMAGE_NAME"
                  echo "DOCKER_PORT: $DOCKER_PORT"
                  echo "Github repository: ${{ github.repository }}"
                  echo "Github run ID: ${{ github.run_id }}"
                  docker login --password ${{ secrets.GITHUB_TOKEN }} --username ${{ github.actor }} ghcr.io
                  docker stop $DOCKER_IMAGE_NAME && docker rm $DOCKER_IMAGE_NAME || true
                  docker system prune -a -f
                  docker pull ghcr.io/${{ github.repository }}:${{ github.run_id }}
                  docker run -d --name $DOCKER_IMAGE_NAME --restart always -e VAULT_ADDR=${{ secrets.VAULT_ADDR }} -e VAULT_TOKEN=${{ secrets.VAULT_TOKEN }} -p 12000:8080 ghcr.io/${{ github.repository }}:${{ github.run_id }}
